//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinaryEntities : DbContext
    {
        private static VeterinaryEntities _ctx;

        public static VeterinaryEntities GetContext()
        {
            if (_ctx == null)
                _ctx = new VeterinaryEntities();
            return _ctx;
        }
        public VeterinaryEntities()
            : base("name=VeterinaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeAnimal> TypeAnimals { get; set; }
        public virtual DbSet<TypeBreed> TypeBreeds { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
